export const PAY_RATES_CATEGORIES = [
  { id: "1", label: "Full-Time" },
  { id: "2", label: "Part-Time" },
  { id: "3", label: "Casual" },
];

export const PAY_RATES = [
  {
    id: "full-time-1",
    category: "Full-Time",
    label: "LEVEL 1",
    typeId: "1",
    categoryId: "1",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
  {
    id: "full-time-2",
    category: "Full-Time",
    label: "LEVEL 2",
    typeId: "2",
    categoryId: "1",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
  {
    id: "full-time-3",
    category: "Full-Time",
    label: "LEVEL 3",
    typeId: "3",
    categoryId: "1",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
  {
    id: "part-time-1",
    category: "Part-Time",
    label: "LEVEL 1",
    typeId: "4",
    categoryId: "2",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
  {
    id: "part-time-2",
    category: "Part-Time",
    label: "LEVEL 2",
    typeId: "5",
    categoryId: "2",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
  {
    id: "part-time-3",
    category: "Part-Time",
    label: "LEVEL 3",
    typeId: "6",
    categoryId: "2",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
  {
    id: "casual-1",
    category: "Casual",
    label: "LEVEL 1",
    typeId: "7",
    categoryId: "3",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
  {
    id: "casual-2",
    category: "Casual",
    label: "LEVEL 2",
    typeId: "8",
    categoryId: "3",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
  {
    id: "casual-3",
    category: "Casual",
    label: "LEVEL 3",
    typeId: "9",
    categoryId: "3",
    note: "Non shift workers are entitled to an unpaid 30-60 mins break after working a maximum of 4.5 hours All day or broken shift workers are entitled to a paid 10 min morning tea break and a paid 10 min afternoon tea break.",
  },
];
